.TH "DGVALIDATOR" "1" "29 juin 2019" "dgvalidator" ""

.SH NOM
dgvalidator \- validateur de kit de batterie drumgizmo

.SH SYNOPSIS
\fBdgvalidator\fR <fichier_de_kit_de_batterie>|-h|--help

.SH "DESCRIPTION"
.PP
\fBDgvalidator\fR est un outil de validation simple pour les fichiers de kit de
batterie drumgizmo.
.PP
Dgvalidator va essayer de charger le kit de batterue pointé par le fichier de
kit batterie et de le valider. Il valide à la fois le xml du kit de batterie et
tous les fichiers d'instruments qui y sont référencés, ainsi que la sémantique
du contenu - y compris la vérification de l'existence et de la validité de tous
les fichiers audio référencés par ces instruments.

.SH "OPTIONS"
.PD 0
.RE
\fB-h, --help\fR
.RS 7
Imprimer l'aide en ligne de commande et quitter.

.RE
\fBfichier_de_kit_de_batterie\fR
.RS 7
Le fichier de kit de batterie à vérifier.

.RE
.SH "BOGUES"
Signaler les bogues http://www.drumgizmo.org/wiki/doku.php?id=bugs.

.SH "INFORMATIONS COMPLÉMENTAIRES"
Pour plus d'informations, visitez le site http://www.drumgizmo.org.

.PP
Cette page de manuel en français a été traduite par Olivier HUMBERT
.B <trebmuh@tuxfamily.org>,
dans le cadre du projet LibraZiK (mais peut être utilisée par d'autres).
