######################################################################
# Automatically generated by qmake (2.01a) Fri May 3 14:05:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += img2c.cc
