top_srcdir=..
include Makefile.am.plugingui

CFLAGS=-DSTANDALONE -DWIN32 -DUSE_THREAD
LDFLAGS=-mwindows
#-lgdi32

OBJECTS=$(PLUGIN_GUI_SOURCES:.cc=.o)

all: $(PLUGIN_GUI_SOURCES) plugingui.exe

plugingui.exe: $(OBJECTS)
	g++ $(OBJECTS) $(LDFLAGS) -o $@

%.o: %.cc
	g++ -O3 -c $(CFLAGS) $< -o $@

clean:
	del -rf *.o plugingui.exe
