#!/bin/bash

TEST=`echo -n $1 | cut -d'.' -f1`
UPPER=`echo $TEST | tr 'a-z.' 'A-Z_'`
OUTPUT=test_$TEST
DEFINE=TEST_$UPPER

SCRIPTDIR=`dirname $0`

COMPILE="g++ -DHAVE_CONFIG_H -I$SCRIPTDIR -g -Wall -Werror -D$DEFINE -o $OUTPUT $*"

echo -e "\033[0;2mTesting $TEST:"
echo Testing $TEST: > $OUTPUT.log

echo -n "* Compiling $TEST test"
echo Compiling $TEST test: > $OUTPUT.log
echo ${COMPILE} >> $OUTPUT.log

if ${COMPILE} >> ${OUTPUT}.log 2>&1; then
	echo -e "\r\t\t\t\t\t\t[\033[1;32mSuccess\033[0;2m]"
	echo "[Success]" >> $OUTPUT.log

	echo -n "* Running   $TEST test"
	echo Running $TEST test: >> $OUTPUT.log
#	gdb ./$OUTPUT --eval-command=run 
	if ./$OUTPUT >> $OUTPUT.log 2>&1; then
		echo -e "\r\t\t\t\t\t\t[\033[1;32mSuccess\033[0;2m]"
		echo "[Success]" >> $OUTPUT.log
	else
		echo -e "\r\t\t\t\t\t\t[\033[1;31mFailure\033[0;2m]"
		echo "[Failure]" >> $OUTPUT.log
		rm -f $OUTPUT
	fi
else
	echo -e "\r\t\t\t\t\t\t[\033[1;31mFailure\033[0;2m]"
	echo "[Failure]" >> $OUTPUT.log
fi

echo